# Generated by Django 2.2.3 on 2019-09-26 20:26

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to=document.models.get_file_name)),
                ('md5sum', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.EmailField(max_length=254)),
                ('zip', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
